### ISSUE TITLE
wakatime agentName not working

### ISSUE THREAD

**Issue by bigfei** [uioporqwerty/joplin-plugin-wakatime#1]
According to the vscode plugin [code](https://github.com/wakatime/vscode-wakatime/blob/402a3df773ea58a6384e7fef3e4bf15dcba74ff2/src/wakatime.ts#L455), there is a space between the editor version and the plugin name
```javascript
let user_agent =
      this.agentName + '/' + vscode.version + ' vscode-wakatime/' + this.extension.version;
```
I am selfhosting the wakatime compatible alternative [wakapi](https://github.com/muety/wakapi), the current user-agent makes the joplin plugin show as unknown:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/207260/198912104-4035707c-7dd8-43dd-b285-df85fa278f40.png">

**Comment by uioporqwerty** [comment]
@bigfei This unknown editor issue exists on the WakaTime as well so I'm suspecting WakaTime needs to add support on their end to identify the user agent as joplin. I'm not sure how wakapi works on this front. 

I tried to get the version info from joplin but looks like joplin's types from their generator are out of date compared to their documentation. https://joplinapp.org/api/references/plugin_api/interfaces/versioninfo.html

I think the unknown issue will still occur even if we did get a version number though. I'll look into getting the version number without the typing as that should still be possible.

**Comment by uioporqwerty** [comment]
Tried out `joplin.versionInfo` in v2.8.8 of Joplin and looks like that method is undefined although the docs say it should exist :/

**Comment by uioporqwerty** [comment]
Pushed out an update in `v1.0.12` which will assume a joplin version number of 2.8.8 until the v2.9.x version, which introduces the `versionInfo` API, is available. Not sure if this will fix the user agent issue above though. Might still say unknown.
